### ISSUE TITLE
Please define jquery dependency in wp_register_script

### ISSUE THREAD

**Issue by sbrajesh** [boonebgorges/bp-group-reviews#14]
Hi Boone,
on some of the occasions the plugin throws error  call to undefined method "jQuery" because of the loading order.

The issue is easy to solve and adding jquery as the dependency solves the issue.

We need to change the line 42 in bp-group-reviews.php (current stable) in the function load_js,
 from
`
wp_register_script( 'bp-group-reviews', BP_GROUP_REVIEWS_URL . 'js/group-reviews.js');
`
to
`
wp_register_script( 'bp-group-reviews', BP_GROUP_REVIEWS_URL . 'js/group-reviews.js' ,array("jquery"));
`

Thanks for the nice plugin :)

Brajesh

**Comment by boonebgorges** [comment]
Ensure that JS requires jQuery. Closed by 6ef267635d63a060e169ff2f9489354b15e6907a. Props Brajesh

**Comment by boonebgorges** [comment]
Thanks for the heads-up, Brajesh!
